# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "PKUcoldkeyboard"
repo_name: "arxiv-daily"
show_authors: True
show_links: True
show_badge: True
max_results: 10

publish_readme: True
publish_gitpage: True
publish_wechat: False

# file paths
json_readme_path: './docs/cv-arxiv-daily.json'
json_gitpage_path: './docs/cv-arxiv-daily-web.json'
json_wechat_path: './docs/cv-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
keywords:
    "Brain Simulation":
        过滤: 
            ["Brain Simulation", "Neural Network Simulation", "Neuroscience Simulation"]
    "Neural Plasticity":
        过滤: 
            ["Neural Plasticity", "Synaptic Plasticity", "Hebbian Learning"]
    "Cortical Columns":
        过滤: 
            ["Cortical Columns", "Cerebral Cortex", "Neocortex"]
    "Spiking Neural Networks":
        过滤: 
            ["Spiking Neural Networks", "SNN", "Neuromorphic Computing"]
    "Neurological Disorders":
        filters: 
            ["Neurological Disorders", "Neurodegenerative Diseases", "Brain Diseases"]
    "Computational Neuroscience":
        filters: 
            ["Computational Neuroscience"]
