# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "PKUcoldkeyboard"
repo_name: "arxiv-daily"
show_authors: True
show_links: True
show_badge: True
max_results: 10

publish_readme: True
publish_gitpage: True
publish_wechat: False

# file paths
json_readme_path: './docs/cv-arxiv-daily.json'
json_gitpage_path: './docs/cv-arxiv-daily-web.json'
json_wechat_path: './docs/cv-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
keywords:
    "Brain Simulation":
        filters: 
            ["Brain Simulation", "Neural Network Simulation", "Neuroscience Simulation"]
    "Spiking Neural Networks":
        filters: 
            ["Spiking Neural Networks", "SNN", "Neuromorphic Computing"]
    "Neuromorphic Computing":
        filters:
            ["Neuromorphic Computing", "Neuromorphic Systems", "Neuromorphic Engineering", "Neuromorphic Hardware"]
    "Neural Coding":
        filters:
            ["Neural Coding", "Neural Code", "Coding in Neural Networks", "Neural Representation"]
    "Brain Modelling and Simulation":
        filters:
            ["Computational Brain Modelling", "Brain Simulation", "Neural Circuit Modelling", "Multiscale Brain Modelling"]
    "High Performance Computing for Neuroscience":
        filters:
            ["High Performance Computing in Neuroscience", "Supercomputing for Brain Simulation", "Parallel Computing for Neural Modelling", "Big Data in Neuroscience"]
    "Neuroinformatics":
        filters:
            ["Neuroinformatics", "Neural Data Analysis", "Neural Data Mining", "Neural Databases"]
    "Neuromorphic Engineering":
        filters:
            ["Neuromorphic Engineering", "Neuromorphic Devices", "Neuromorphic Circuits", "Neuromorphic Sensors"]